apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@jsuri.com # replace for your valid email
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
#    - selector: {}
#      http01:
#        ingress:
#          class: traefik
    - dns01:
        cloudflare:
          email: me@jsuri.com  # Replace with your Cloudflare account email
          apiTokenSecretRef:
            name: cloudflare-api-key-secret
            key: api-key
