apiVersion: v1
kind: Service
metadata:
  name: firetv-hook-kitchen
  namespace: firetv
spec:
  ports:
    - name: "adb"
      port: 5038
      targetPort: 5037
  selector:
    app: firetv
  type: LoadBalancer
