apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-data
  name: compreface-db
  namespace: compreface
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi  # Match or be less than the PV's capacity
  volumeName: compreface-pv  # Bind explicitly to the PV created above
  storageClassName: ''
