apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: cf-fe
  namespace: compreface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - image: 'exadel/compreface-fe:latest'
          name: cf-fe
          ports:
            - containerPort: 80
          env:
            - name: CLIENT_MAX_BODY_SIZE
              value: "10M"
            - name: PROXY_READ_TIMEOUT
              value: "60000ms"
            - name: PROXY_CONNECT_TIMEOUT
              value: "10000ms"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe
  name: compreface-ui
  namespace: compreface
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: fe
