apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azcopy-sas-token
  namespace: azcopy
spec:
  encryptedData:
    SASTOKEN: AgACo83NeOeBg3vwLkeapMkrABi+kGaQNdUGqatz6lKYSMpr0PzjigsjDebWLgVMlssJg2q/LQChMVAq7aemZdmAnfv2PEYK3vSfmf9n+OY3j00hns2iWlaBBnIqN+Wq76h+qLScCtYIfZAuq9onVOLD2X0ltGiQNiKut7YH2X2lyQV5GjNVE+TF9V55WTCZTxu6lCEiHXwpSb1iCQv3BaRHCc0AWShwYglNXwJ6KRHGnRVDaZNY6RTOmdGFFgcNrJYBecsiu7adsA7FJLa4EpuAxg1BMB4aDx7QEQYBPVkMWLBum3xussz//6mFSGWxPzUHA4sgD+xRRnoc7dm7q/k2V8Mb8dtR/HTirJsm98tCSeilM6exAd0OoWwYqmDdqrnSlXwdsUZa/ihPdaElrcsr7ITncbN465xTxfwwtgwcOxhXXC4L5p53wUgRNQHxazc8e6RzBtHEYrqcEv34Y6Je4qiD1/wdxlvRa3sz5/192NDkp0cEyT3WWoA2OQuXTBcb+I/DS0Keu8FoDVc/mLyTmMs9PBpn8AdZwtmEC0pvJ9hQ0nJC5stCblGWXPoexOVo9JGb4pFB9AGiiwYS2O8mlghH7TfoCKIsvzTXj88528ah25yxcHnCGLI4YEmi5yIvNyEN7mHyPItLwFOR1qidk696nL2wwWxVLS8qIjkfYIEYsxZ7L2PoX0wVxaYH7s6oxp6/x7HjJf3K81dKmQ9CqeDRWoixjEBPYUAmWetXHSJc3tLHFpFlbiS+PVdb9Mji4Fg6DEarQhFzKZcnCwu0aXTkIbPL4s175V9onyIP4DOXQxlHz8DkZZghd2OOtvU6zdF4Rq3vCLv2Y96S54fjpojMgmlE7QEaz/QFnL0GVRYSUuHGIkuPas1oXimx
  template:
    metadata:
      creationTimestamp: null
      name: azcopy-sas-token
      namespace: azcopy