apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azcopy-sas-token
  namespace: azcopy
spec:
  encryptedData:
    SASTOKEN: AgBEnHmz7KOmVYDpg/ocM29fSQsa4h1X3f5cmycMp940yk9swghrVbit8CMTyGFpF1nSw66uzh4zc9bHi3zq0mkMV6LmwB273hk80TbezunlbhvcA2OKeDFVUZim2jhPYufIP62cBLQDFP/mCrxvgkfqdid3WVxc15uZQ/b7Rc2vD73ZVqJ+JGpCSwt3gt7JqGE6rwPHY09epXgmlI+NkIjh1pU9nYSi5HzDuGgnsasGy1+iIlzEXDZh3nfdZCeBVnKuchSwAYx0nMqnHh+sn5udmczuZ4C2Si18asb7+N592GRgXISUKZcjCx0Aio4HKP8QtUL/uxy83rYgMHw8zQ7C3LElJPtdDSX+0yS4dEjIO3j7a1yL5OoHqZHMZhcn1Z7mtFEGnma7ZTcmj6Iy3BZCFjDlVOtr7elDSEi/9oc7YejZndnx511tXy3yqlSpPMKNiPmcOAvcjjHZEorijpPbvJ12YJAsHL7f1mRr4vPzYDe1QWdClzFi2/21mF0OOvBXCOyuwDinHtoe799bYp5W/AI+2Wem18vWcuiS7rvu2PAzajza9bcEYsR4Pr35Dz9X7eae8Ze68swUbZPDHoJk1oQRrXxCIlybCp4IH0vC44S/Do/Dd6yJ8gIH7H5Ca7mk6Cit5jKWwxGbzMYc3MSfzzimPuVuOcZS0hfWPOTVShwSNWRGs87IH/eeR5Egz+Z+O5DePcYAe2jDcp4V3GMuNveH3pHvpor6eBhCvHXY1/+swLPyesJH4qSacFP4eZ2w/S9OKsZq3BktyuR7IuzN0UtI6X6xO5UIkqcr+Y+Vrcgj9asRSZLIr3lhmcb6h6rukmQqPAwZWviP8ze6mTjR3FFS5l88gynWEfRsYkS7/KSl+JLjfQ==
  template:
    metadata:
      creationTimestamp: null
      name: azcopy-sas-token
      namespace: azcopy
    type: Opaque