kind: PersistentVolume
apiVersion: v1
metadata:
  name: azcopy-logs-pv
  namespace: azcopy
  labels:
    app: azcopy
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k3s/projects/azcopy/logs # Static path on the NFS server
    server: 192.168.1.238               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
