kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k3s-projects-pvc
  namespace: azcopy
  labels:
    app: azcopy
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5000Gi  # Match or be less than the PV's capacity
  volumeName: k3s-projects-pv  # Bind explicitly to the PV created above
  storageClassName: ''
