kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ext-photos-library-pvc
  namespace: azcopy
  labels:
    app: azcopy
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi  # Match or be less than the PV's capacity
  volumeName: ext-photos-library-pv  # Bind explicitly to the PV created above
  storageClassName: ''
