apiVersion: batch/v1
kind: CronJob
metadata:
  name: azcopy-midnight
  namespace: azcopy
spec:
  schedule: "0 0 * * *"  # This schedule runs the job every day at midnight
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: azcopy
              image: peterdavehello/azcopy:10.11.0
              stdin: true
              tty: true
              env:
                - name: AZCOPY_BUFFER_GB
                  value: "4"
              volumeMounts:
                - name: k3s
                  mountPath: /k3s
                - name: logs
                  mountPath: /root/.azcopy
              command: ["/bin/sh"]
              args: ["-c", "azcopy sync /k3s 'https://nasbackupstore.blob.core.windows.net/k3s?<SAS TOKEN>' --cap-mbps 50 --exclude-path='projects/frigate/media;projects/immich/library/thumbs;projects/nextcloud/data/appdata_oc37w82ykyup'"]
              resources:
                requests:
                  memory: "4096Mi"
                  cpu: "600m"
                limits:
                  memory: "4572Mi"
                  cpu: "2"
          restartPolicy: Never
          volumes:
            - name: k3s
              persistentVolumeClaim:
                claimName: k3s-projects-pvc
            - name: logs
              persistentVolumeClaim:
                claimName: azcopy-logs-pvc
