kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azcopy-logs-pvc
  namespace: azcopy
  labels:
    app: azcopy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Match or be less than the PV's capacity
  volumeName: azcopy-logs-pv  # Bind explicitly to the PV created above
  storageClassName: ''
