apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Match or be less than the PV's capacity
  volumeName: grafana-pv  # Bind explicitly to the PV created above
  storageClassName: ''
