kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ext-immich-library-pvc
  namespace: immich
  labels:
    app: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi  # Match or be less than the PV's capacity
  volumeName: ext-immich-library-pv  # Bind explicitly to the PV created above
  storageClassName: ''