apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: default # Use the appropriate namespace
spec:
  redirectScheme:
    scheme: https
    permanent: true
