apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  namespace: home-assistant
spec:
  capacity:
    storage: 5Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/NAS/k3s/projects/home-assistant  # Static path on the NFS server
    server: 192.168.1.27               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
