apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match or be less than the PV's capacity
  volumeName: home-assistant-pv  # Bind explicitly to the PV created above
  storageClassName: ''
