apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant


---

# home-assistant-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: home-assistant-storage
          mountPath: /config
          subPath: config
      volumes:
      - name: home-assistant-storage
        persistentVolumeClaim:
          claimName: home-assistant-pvc
