apiVersion: v1
kind: Namespace
metadata:
  name: zigbee

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee-data-pv
  namespace: zigbee
  labels:
    app: zigbee
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/NAS/k3s/projects/zigbee2mqtt  # Static path on the NFS server
    server: 192.168.1.27               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee-data-pvc
  namespace: zigbee
  labels:
    app: zigbee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Match or be less than the PV's capacity
  volumeName: zigbee-data-pv  # Bind explicitly to the PV created above
  storageClassName: ''

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: zigbee
spec:
  selector:
    matchLabels:
      app: zigbee
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-iot",
            "namespace": "default",
            "mac": "70:cb:57:bb:d4:a2",
            "ips": ["192.168.1.194/24"]
          }]
    spec:
      containers:
      - image: koenkk/zigbee2mqtt:latest
        name: zigbee
        env:
        - name: "ZIGBEE2MQTT_DATA"
          value: "/data"
        - name: "ZIGBEE2MQTT_CONFIG_MQTT_SERVER"
          value: "mqtt://mosquitto-service.mosquitto.svc.cluster.local:1883"
        - name: "ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC"
          value: "zigbee2mqtt"
        - name: "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN"
          value: "false"
        - name: "ZIGBEE2MQTT_CONFIG_SERIAL_PORT"
          value: "/dev/ttyUSB0"
        #- name: "ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY"
        #  value: "GENERATE"
        - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
          value: "jas"
        - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
          value: "password"
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
          value: "true"
        - name: "TZ"
          value: "Europe/London"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: usb
          mountPath: /dev/ttyUSB0
        - name: udev
          mountPath: /run/udev
        securityContext:
          privileged: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zigbee-data-pvc
      - name: usb
        hostPath:
          path: /dev/ttyUSB0
      - name: udev
        hostPath:
          path: /run/udev

---

apiVersion: v1
kind: Service
metadata:
  name: zigbee
  namespace: zigbee
  labels:
    app: zigbee
spec:
  ports:
  - port: 8085
    targetPort: 8080
  selector:
    app: zigbee
  type: LoadBalancer


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee-private
  namespace: zigbee
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: zigbee
spec:
  rules:
  - host: zigbee.jsuri.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: zigbee
            port:
              number: 8085
