apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee-data-pv
  namespace: zigbee
  labels:
    app: zigbee
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /k3s/projects/zigbee2mqtt  # Static path on the NFS server
    server: 192.168.1.238               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
