apiVersion: v1
kind: Service
metadata:
  name: firetv-hook-masterbed
  namespace: firetv-masterbed
spec:
  ports:
    - name: "adb"
      port: 5037
      targetPort: 5037
  selector:
    app: firetv-masterbed
    instance: masterbed
  type: LoadBalancer
