apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firetv-masterbed-pvc
  namespace: firetv-masterbed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi  # Match or be less than the PV's capacity
  volumeName: firetv-masterbed-pv  # Bind explicitly to the PV created above
  storageClassName: ''
