kind: PersistentVolume
apiVersion: v1
metadata:
  name: firetv-masterbed-pv
  labels:
    app: firetv-masterbed
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nas/k3s/projects/firetv # Static path on the NFS server
    server: 192.168.1.27               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
