kind: PersistentVolume
apiVersion: v1
metadata:
  name: icloudpd-photos-pv
  namespace: icloudpd
  labels:
    app: icloudpd
spec:
  capacity:
    storage: 100Gi  # Adjust the storage size as needed
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/NAS/k3s/k3s/projects/nextcloud/data/jasjeet/files/Photos # Static path on the NFS server
    server: 192.168.1.27               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
