kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: icloudpd-photos-pvc
  namespace: icloudpd
  labels:
    app: icloudpd
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi  # Match or be less than the PV's capacity
  volumeName: icloudpd-photos-pv  # Bind explicitly to the PV created above
  storageClassName: ''