apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-server

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflare-server
spec:
  encryptedData:
    token: AgAwUBQxo1MLuR8/KDTxLsg2GrFMKB+wYPJ6MSMZ05zuIpV/UeWpg636rasUj25GQ61WzXw0f7lg7hxQOOeYiT1oPyz4YpHfghhn5TbgGHjXD07j+iDHyRZucDUiLox9EckzELlIG6bbeJWJCexPww39nHeVhs16W+>
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cloudflare-server
    type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: cloudflare-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
        name: cloudflare
    spec:
      containers:
        - name: cloudflare
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(CLOUDFLARE_TOKEN)"  # Use environment variable
          env:
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-token  # Name of the decrypted Secret
                  key: token  # Key containing the token