apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-server

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflare-server
spec:
  encryptedData:
    token: AgCAhxHZWon9F/y42o8P3zCpYFlITyDZ+/ZvgMqHCtYBCLeHIX12i1I0AgBB2xK2xkl1KOZJ0Bp4U8bi3QxtvMqYaptnZIpSKKMtlrAEnRICBbEVPFAhZLiN+Cm1dcsOr8RJuiNk5K0dG4RsKzYcsugLot6UbL0AlmHIwemb4oHG8+hcHpo6YBY9LonAlFCC2gzR5n60cKbX49J6o7KT6v07bYkLYz90MxNzXrY/NHixchyoin81GTHZ9ESpU7QGuYBv9U5Bu34Pk7zmLcupi9XIHvgU8idz6SxzNowCffOL/y7Nhg1+J0wxTIXzqvv2z3qCDS+zkXchGFKmTEjfXLQx4YUfBKkvneirNwbfXJHJB5RZPA9kKpr/dA/cvyqbT5ClRRMOVfvwMlDbZgyTvVXcasM2T+fCU+IQSfucLnCrxr6VaX3XTut+erM5JzUyyzr5fTzt9oAzBLucNi3G3Eg0s182CaQmnCzdmj1mMybgHWT2/pv382HBWhAFfQSb6zu193ByjQiD0zDM2C1P9MEqElthJSvkj2Em5TpNpSH70vzetGXP0qq0snUQPx5/IAXkI07EN2d1z/ZsJhjSrFopHSaxxUVrvaTNcspzmLGYpOwB+7B059qmtFjmmW8r1lhxzngrKliv/WCK2Kn5EZ1ia75tYzYPlE+ynC+4fVOtychTkPCyflggPgm7GfoRUl7BHkYG+FKLAf+iuRw/EwFkpL3XJnz4reOfzc74t17Fn1ycV7Q1d6XVZqRZPfG7pTa/g9nwRkuII0MNpcqU8NKSW8D1CS+lGHO6k7z3NTi9hV5U6l7L0L1ek2m2lmBND3hPF5rGGtWLxn/XVGA0FSXPCz9CzSfsoQ61ec4I9BP6y7flc/rD7jWuBSTRiPKJ6P2VM9Y0DXsEyoctPUYB+96Cee2PvP9SWGm77KY2L/CHj6RWqxVLDhrk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cloudflare-server
    type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: cloudflare-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
        name: cloudflare
    spec:
      containers:
        - name: cloudflare
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "${CLOUDFLARE_TOKEN}"  # Use environment variable
          env:
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-token  # Name of the decrypted Secret
                  key: token  # Key containing the token