apiVersion: v1
kind: Namespace
metadata:
  name: redis-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: redis-server
  labels:
    app: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - image: redis:alpine
          name: redis-server
          ports:
            - containerPort: 6379
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: redis-server
  labels:
    app: redis-server
spec:
  ports:
    - port: 6379
  selector:
    app: redis-server