kind: PersistentVolume
apiVersion: v1
metadata:
  name: restic-data-pv
  namespace: restic
  labels:
    app: restic
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k3s/projects/restic # Static path on the NFS server
    server: 192.168.1.238               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
