kind: PersistentVolume
apiVersion: v1
metadata:
  name: files-to-backup-pv
  namespace: restic
  labels:
    app: restic
spec:
  capacity:
    storage: 5000Gi  # Adjust the storage size as needed
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/nas/k3s/projects # Static path on the NFS server
    server: 192.168.1.27               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
