apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Match or be less than the PV's capacity
  volumeName: nextcloud-config-pv  # Bind explicitly to the PV created above
  storageClassName: ''
