apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 1000Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k3s/projects/nextcloud  # Static path on the NFS server
    server: 192.168.1.238               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
