apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi  # Match or be less than the PV's capacity
  volumeName: nextcloud-data-pv  # Bind explicitly to the PV created above
  storageClassName: ''
