apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-config-pv
  namespace: mosquitto
spec:
  capacity:
    storage: 5Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k3s/projects/mosquitto  # Static path on the NFS server
    server: 192.168.1.238               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
