apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: mosquitto
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
