apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: ws
      port: 8080
      targetPort: 8080
      protocol: TCP
  externalIPs:
  - 192.168.1.159
