apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match or be less than the PV's capacity
  volumeName: frigate-config-pv  # Bind explicitly to the PV created above
  storageClassName: ''
