apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebox-pv
  namespace: homebox
spec:
  capacity:
    storage: 50Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k3s/projects/homebox  # Static path on the NFS server
    server: 192.168.1.238               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
