apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-pvc
  namespace: homebox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi  # Match or be less than the PV's capacity
  volumeName: homebox-pv  # Bind explicitly to the PV created above
  storageClassName: ''
